### ISSUE TITLE
Error  exécution object_tracker.py  

### ISSUE THREAD

**Issue by Polozeed** [anushkadhiman/ObjectTracking-DeepSORT-YOLOv3-TF2#2]
Hello, 

This is my error :     self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 86: invalid continuation byte

When i execute object_tracker.py 

thx and have a good day :)

**Comment by anushkadhiman** [comment]
@Polozeed 
Can tell me, at which line it shows this error? When u execute object_tracker.py file.

**Comment by priyankap-nicn** [comment]
I got this error 
tensorflow.python.framework.errors_impl.NotFoundError: model_data/mars-small128.pb; No such file or directory

**Comment by hemanth-mudusu** [comment]
> I got this error
> tensorflow.python.framework.errors_impl.NotFoundError: model_data/mars-small128.pb; No such file or directory

--Yes I got the same error. And I checked their repository but mars-small128.pb file is not existed there

**Comment by anushkadhiman** [comment]
Hi,

I have uploaded the mars-small128.pb file in model_data folder. So, I'm closing this issue as it will solve the problem, but feel free to report back.

**Comment by topinfrassi01** [comment]
Hi @anushkadhiman ,

I had the same problem.

mars-small128.pb has been uploaded to `model_data/coco` but in the code it searchs for it in `model_data`.

After changing line 23 of object_tracker.py from `model_filename = 'model_data/mars-small128.pb'` to `model_filename = 'model_data/coco/mars-small128.pb'`, this bug in particular seems fixed however the track.mp4 file has no bounding boxes at all.
